# netlify.toml  (must be named exactly this)
[build]
  publish = "."
  functions = "netlify/functions"

# This redirect is optional, but valid. It simply allows
# / .netlify/functions/<name> to be called directly.
